galaxy_info:
  author: Nicolas Braud-Santoni
  description: Securely deploys dotfiles
  license: ISC

  min_ansible_version: 2.0

  platforms:
  - name: Debian
    versions: [ all ]
  - name: Ubuntu
    versions: [ all ]
  - name: FreeBSD
    versions: [ all ]

  galaxy_tags:
    - config
    - dotfiles
    - user

dependencies: []
