---
- name: Create ZFS deb dataset
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}"
    state: present
    extra_zfs_properties:
      compression: lz4
      mountpoint: "{{ debian__zfs_path }}"
  become: yes

- name: Create ZFS datasets
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}/{{ item }}"
    state: present
  with_items: [ buildarea, schroot, cache ]
  become: yes
