---
- name: "ZFS : Create main dataset"
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}"
    state: present
    extra_zfs_properties:
      compression: lz4
      mountpoint: "{{ debian__path }}"
  become: yes

- name: "ZFS : Create datasets"
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}/{{ item }}"
    state: present
  with_items: [ buildarea, schroot, cache ]
  become: yes

- name: "ZFS : Create datasets for schroots"
  zfs:
    name: "{{ debian__zpool_name }}/{{ debian__zfs_dataset }}/schroot/{{ item.suite }}"
    state: present
  with_items: "{{ debian__schroots }}"
  loop_control:
    label: "{{ item.suite }}"
  become: yes
