---
- block:
    - name: Set permissions on the cache directory
      file:
        path: "{{ debian__path }}/cache"
        owner: apt-cacher-ng
        group: apt-cacher-ng
        mode:  0755

    - name: Configure apt-cacher-ng
      template:
        dest: /etc/apt-cacher-ng/acng.conf
        src: acng.conf.j2
      notify: Restart apt-cacher-ng

    - name: Configure apt-cacher-ng Debian backend
      copy:
        dest: /etc/apt-cacher-ng/backends_debian
        content: |
          https://deb.debian.org/debian
      notify: Restart apt-cacher-ng

  become: yes

- meta: flush_handlers
