---
- name: Install required packages
  when: dotfiles__install_packages
  become: yes
  pkgng:
    state: present
    name:
      - direnv
      - git
      - gnupg
      - stow
      - zsh

- name: Install extra packages
  when: dotfiles__install_extra_packages
  become: yes
  pkgng:
    state: present
    name:
      - emacs-nox
      - htop
      - ipcalc
      - py36-httpie
      - mosh
      - mtr-nox11
      - tig
      - tmux
