---
# tasks file for nbraud.dotfiles
- name: Install required packages
  apt:
    name:
      - debian-keyring
      - direnv
      - git
      - gnupg2
      - stow
      - zsh
    state: present

  become: yes
  when: dotfiles__install_packages

- name: Install extra packages
  apt:
    name:
      - command-not-found
      - emacs
      - htop
      - httpie
      - ipcalc
      - man-db
      - manpages
      - mosh
      - mtr-tiny
      - net-tools
      - qalc
      - tig
      - tmux
    state: present

  become: yes
  when: dotfiles__install_extra_packages
